### ISSUE TITLE
Incomplete path contexts

### ISSUE THREAD

**Issue by malodetz** [JetBrains-Research/psiminer#11]
While evaluating [code2seq](https://github.com/JetBrains-Research/code2seq) model on projects apache__hbase and wildfly__wildfly from test part of [java-med](https://s3.amazonaws.com/code2seq/datasets/java-med.tar.gz) dataset, preprocessed via psiminer (see the [config](https://github.com/JetBrains-Research/psiminer/blob/a3a9a5f6843df37ecfb82d16f18375e34d20cf25/config.json)) I got errors:
```
wildfly__wildfly
Global seed set to 7
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Testing: 0it [00:00, ?it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Testing:  93%|████████████████████████████████████████████████████████████████▍    | 14/15 [00:13<00:00,  1.14it/s]Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/fine-tuning/fine-tuning-ml-models/scripts/test_all.py", line 42, in <module>
    test_all(args.dataset, args.model, args.results)
  File "/home/ubuntu/fine-tuning/fine-tuning-ml-models/scripts/test_all.py", line 25, in test_all
    metrics = test_single(model_path, os.path.join(PREPROCESSED_DATASETS_DIR, project_name))
  File "/home/ubuntu/fine-tuning/fine-tuning-ml-models/scripts/test_single.py", line 21, in test_single
    results = test(model_path, project_path, batch_size=1)
  File "dependencies/code2seq_repo/code2seq/test.py", line 57, in test
    return trainer.test(model, datamodule=data_module)
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in test
    results = self._run(model)
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
    self.dispatch()
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 795, in dispatch
    self.accelerator.start_evaluating(self)
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 99, in start_evaluating
    self.training_type_plugin.start_evaluating(trainer)
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 148, in start_evaluating
    self._results = trainer.run_stage()
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 806, in run_stage
    return self.run_evaluate()
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in run_evaluate
    eval_loop_results = self.run_evaluation()
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 954, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "dependencies/code2seq_repo/code2seq/dataset/path_context_dataset.py", line 82, in __getitem__
    splitted_contexts = [self._split_context(str_contexts[i]) for i in context_indexes]
  File "dependencies/code2seq_repo/code2seq/dataset/path_context_dataset.py", line 82, in <listcomp>
    splitted_contexts = [self._split_context(str_contexts[i]) for i in context_indexes]
  File "dependencies/code2seq_repo/code2seq/dataset/path_context_dataset.py", line 51, in _split_context
    from_token, path_nodes, to_token = context.split(",")
ValueError: not enough values to unpack (expected 3, got 2)
Exception ignored in: <function tqdm.__del__ at 0x7ff4422eeaf0>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/tqdm/std.py", line 1122, in __del__
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/tqdm/std.py", line 1335, in close
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/tqdm/std.py", line 1514, in display
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/tqdm/std.py", line 1125, in __repr__
  File "/home/ubuntu/anaconda3/envs/fine-tuning-env/lib/python3.8/site-packages/tqdm/std.py", line 1475, in format_dict
TypeError: cannot unpack non-iterable NoneType object 
```
It seems that part of the path context is missing. Note, that it is also the last line of the .c2s file, so the preprocessed file looks uncompleted.

**Comment by SpirinEgor** [comment]
Hi!
Could you provide last line of this file?

**Comment by malodetz** [comment]
Here it is:
```
read|element =,46|10|31|13,reader break,153|51|51|25|11|10|11|13,subsystem has|next,3|27|32|158|10|11|13,namespace break,153|51|156|157,case :,83|156|51|153,break element,13|11|26|10|41|41|3,choice|element|encountered switch,155|4|51|154|4|75|10|14,reader break,153|51|51|153,break parse|core|environment|element,13|25|51|4|154|51|156|159,default element,7|41|154|4|51|153,break final,38|10|11|3,of reader,13|13,subsystem xml|stream|exception,28|22|4|25|11|10|14,op|addr required,3|41|87|158|4|51|154|155,switch :,83|156|51|154|4|51|25|13,parse|jdbc|store|element|and|enrich|operation required,13|11|25|5|75|10|14,reader reader,13|27|32|33,!= reader,3|37|36|4|25|11|3,set get,3|11|10|11|25|41|38,final void,29|22|28,xml|stream|exception if,8|5|41|47|28,model|node transactions,14|156|51|154|4|51|25|13,parse|use|journalstore :,83|156|4|158|87|5|8,if :,83|156|4|154|51|75|10|14,reader element,7|41|154|13,element =,46|41|87|32|32|27|3,next|tag //|elements,24|41|10|11|3,of final,38|41|25|26|11|13,model|description|constants unexpected|element,13|10|75|5|51|75|10|13,unexpected|element required,3|41|41|10|11|13,enum|set final,38|41|5|75|10|14,reader switch,155|4|51|25|11|10|40|3,use|jdbc|store void,29|3,<MN> reader,13|26|25|51|51|52|110,true void,29|4|41|49|54|7,element subsystem,13|11|10|11|25|51|75|67,throw model|node,7|41|25|11|13,log|store|address switch,155|4|51|25|26|13,subsystem reader,14|10|75|5|154|4|156|14,jts enum|set,13|3,none|of <MN>,3|4|41|3,log|store|address get|namespace|uri,3|31|10|4|156|157,case <MN>,3|4|41|49|54|7,element final,38|41|87|158|4|75|67,throw list,3|49|37|36|4|25|11|3,set reader,13|26|25|51|51|5|75|67,throw transaction|extension,13|11|26|25|41|38,final protect,3|59|25|14,log|store|operation reader,13|26|25|51|51|25|26|13,reader final,38|41|154|4|51|25|11|3,set if,8|5|154|4|156|157,case address,13|27|41|25|26|11|13,log|store|constants reader,13|26|25|51|156|157,case log|store|address,13|11|26|11|13,log|store|constants break,153|51|4|154|51|156|159,default enum|set,13|11|10|41|41|46,= class,77|129|10|41|41|3,choice|element|encountered throw,67|10|13,unexpected|attribute none|of,3|11|10|41|41|39,boolean choice|element|encountered,13|52|25|11|10|40|13,common|attributes model|node,7|41|25|11|3,add subsystem,14|25|41|38,final xml|extended|stream|reader,7|37|36|4|41|10|11|13,enum|set if,8|5|51|51|5|13,choice|element|encountered xml|stream|exception,28|22|4|59|3,protect final,38|41|25|11|13,address switch,155|4|156|83,: >,55|54|49|41|41|49|54|57,< reader,14|10|75|5|51|51|5|8,if while,45|158|4|51|41|3,element remove,3|11|25|154|4|156|157,case element,13|11|10|41|153,break element,7|41|154|4|51|25|11|3,set throw,67|75|5|51|156|159,default &&,78|32|158|4|51|25|11|3,remove jdbc|store,14|156|51|25|11|10|40|13,common|attributes choice|element|encountered,13|52|51|75|10|13,unexpected|element subsystem,14|25|41|3,log|store|address final,38|41|154|4|51|52|110,true set,3|11|25|41|7,model|node element,13|11|26|10|41|41|49|3,enum|set throw,67|75|5|51|75|67,throw =,46|41|154|155,switch :,83|156|51|153,break model|node,7|54|49|37|36|4|41|46,= set,3|11|14,address //|elements,24|41|49|54|57,< model|node,7|41|59|3,protect break,153|51|51|5|75|67,throw :,83|156|51|154|4|156|83,: reader,13|27|32|5|41|3,address if,8|5|52|46,= reader,13|26|25|153,break true,61|25|51|4|154|51|75|67,throw xml|stream|exception,28|22|4|41|10|11|3,of parse|use|journalstore,13|25|51|156|14,jdbc|store unexpected|attribute,13|10|75|5|41|3,subsystem :,83|156|4|154|51|156|159,default reader,14|10|75|5|25|11|3,set reader,14|10|75|4|154|51|156|83,: element,7|129|10|41|41|3,choice|element|encountered element,7|10|31|3,get|local|name throw,67|10|13,unexpected|element encountered,3|41|87|32|27|13,reader xml|stream|exception,28|22|4|41|47|56,new reader,13|3,get|local|name break,153|51|51|5|13,choice|element|encountered list,3|49|37|36|4|5|8,if enum|set,3|49|41|87|32|32|33,!= element,3|41|154|4|51|52|110,true enum|set,3|49|41|41|3,encountered xml|stream|exception,28|22|4|87|158|4|75|67,throw enum|set,3|49|41|87|32|32|27|13,reader switch,155|10|11|13,namespace choice|element|encountered,13|5|51|4|154|51|75|67,throw element,13|4|51|52|110,true get|attribute|count,3|27|32|5|41|38,final case,157|156|51|153,break break,153|51|51|25|11|10|40|3,use|jdbc|store list,3|37|36|4|41|39,boolean address,13|59|41|47|56,new switch,155|4|51|154|4|51|52|110,true unexpected|element,13|10|75|5|154|4|156|157,case false,89|41|87|32|27|13,reader parse|core|environment|element,13|25|51|51|153,break transactions,14|156|51|154|4|51|153,break if,8|5|51|156|157,case true,61|25|51|51|5|75|67,throw choice|element|encountered,3|41|87|158|4|156|159,default case,157|156|156|159,default reader,13|31|10|41|154|4|156|157,case get,3|11|10|11|25|25|11|13,list >,55|54|49|41|87|32|78,&& =,46|41|25|11|10|11|3,get list,3|37|36|4|41|10|11|3,none|of element,13|4|51|5|75|10|14,reader :,83|156|51|25|26|13,subsystem jts,14|156|156|157,case list,3|49|37|36|4|5|75|67,throw use|journal|store,3|40|10|11|25|51|156|159,default final,38|41|154|4|156|14,object|store parse|use|journalstore,13|26|13,log|store|operation element,7|41|51|156|159,default for|uri,3|11|10|4|51|154|155,switch final,38|41|5|75|10|26|13,required reader,13|27|32|5|41|47|28,model|node element,3|41|154|4|51|153,break new,56|47|41|25|11|10|11|3,get switch,155|4|51|5|8,if throw,67|75|5|41|7,model|node reader,3|37|36|4|41|39,boolean for|name,3|11|10|41|154|4|156|14,use|hornetq|store transactions,14|156|51|154|4|51|25|13,parse|jdbc|store|element|and|enrich|operation element,7|54|49|46,= while,45|32|27|13,reader >,55|54|49|41|41|89,false while,45|158|4|156|159,default required,13|11|25|154|4|156|14,jts log|store|address,13|3,add =,46|41|154|4|51|153,break <MN>,3|4|87|158|4|51|41|3,element throws,23|22|
```

**Comment by SpirinEgor** [comment]
Hmm, it seems that storage wasn't closed properly and PrintWriter didn't flush it buffer. Did PSIMiner produce any output in the end? Like statistic or error message?

**Comment by malodetz** [comment]
Yes, there was an error:
```
Details: Current thread: Thread[DefaultDispatcher-worker-20 @coroutine#7846,6,Idea Thread Group] 2145522645
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1488940502 
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:177)
        at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1033)
        at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:411)
        at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:224)
        at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:212)
        at psi.PsiNode.getToken(PsiNode.kt:31)
        at astminer.paths.PathWorker.retrievePaths(PathWorker.kt:64)
        at astminer.paths.PathMiner.retrievePaths(PathMiner.kt:12)
        at storage.Code2SeqStorage.extractPathContexts(Code2SeqStorage.kt:50)
        at storage.Code2SeqStorage.store(Code2SeqStorage.kt:57)
        at Pipeline$extractDataFromDataset$projectParser$2.invoke(Pipeline.kt:44)
        at Pipeline$extractDataFromDataset$projectParser$2.invoke(Pipeline.kt:10)
        at psi.PsiProjectParser$convertPsiFilesToTreesAsync$2$invokeSuspend$$inlined$map$lambda$1$2.invokeSuspend(PsiProjectParser.kt:66)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-07-21 18:56:50,197 [  23480]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2020.3  Build #IC-203.5981.155 
2021-07-21 18:56:50,197 [  23480]  ERROR - plication.impl.ApplicationImpl - JDK: 11.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-07-21 18:56:50,197 [  23480]  ERROR - plication.impl.ApplicationImpl - OS: Linux 
2021-07-21 18:56:50,302 [  23585]  ERROR - plication.impl.ApplicationImpl - Plugin to blame: Psiminer version: 1.0-SNAPSHOT 
2021-07-21 18:56:50,358 [  23641]  ERROR - plication.impl.ApplicationImpl - Last Action:  

> Task :runIde FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runIde'.
> Process 'command '/home/grey/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_9-linux-x64-b1145.21/jbr/bin/java'' finished with non-zero exit value 137

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
```
But the cause of the exception is not clear.

**Comment by SpirinEgor** [comment]
Then you obviously do not have a full set of paths. The process of mining ended up somewhere in the middle. You should rerun mining to get full data. Btw, did you use the master branch?

**Comment by malodetz** [comment]
Yes. Should I try psiminer_v2?

**Comment by SpirinEgor** [comment]
I add a small fix into the master branch that should avoid this error in the future. Using `v2` is preferable, I hope it will be in master soon. I support all logic for working with PSI trees in it, but I can't guarantee compatibility with already trained networks.
